name: release
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  code:
    uses: cyberuni/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'
      skip-playwright: true

  release:
    needs: code
    uses: cyberuni/.github/.github/workflows/pnpm-release-changeset.yml@main
    secrets: inherit
    with:
      skip-playwright: true
